# 服务器订阅配置
proxy-providers:
  Server:
    type: http
    path: ./Provider/Proxy/Server.yaml
    url: https://sub.hotkids.me
    interval: 3600
    proxy: DIRECT
    header:
      User-Agent:
      - "Clash/v1.18.0"
      - "mihomo/1.18.3"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 600

proxy-groups:
  # 全局代理
  - name: "GLOBAL"
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png
    include-all: true

  # 去广告以及隐私追踪保护、反运营商劫持开关 // 📧 Mail
  - name: "🚧 AdGuard"
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Clubhouse_2.png
    proxies:
      - ⛔️ REJECT
      - 🔘 DIRECT

  # 阻止
  - name: "⛔️ REJECT"
    type: select
    hidden: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Reject.png
    proxies:
      - REJECT

  # 直连
  - name: "🔘 DIRECT"
    type: select
    hidden: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Direct.png
    proxies:
      - DIRECT

rules:
  # GeoIP // RULE-SET,LAN
  - GEOSITE,cn,🔘 DIRECT
  - GEOIP,CN,🔘 DIRECT
  - GEOSITE,geolocation-!cn,🔰 Proxy
