<< Clash/General.yaml

# 服务器订阅配置
proxy-providers:
  Server:
    type: http
    path: ./Provider/Proxy/Server.yaml
    url: https://sub.hotkids.me
    interval: 3600
    proxy: DIRECT
    header:
      User-Agent:
      - "mihomo/1.18.3"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 600
      timeout: 5000
      expected-status: 204

proxy-groups:
  # Global
  # name: "GLOBAL"
  # type: select
  # icon: https://raw.githubusercontent.com/HotKids/Rules/master/Quantumult/X/Images/Color/Inbound.png
  # include-all: true

rules:
  # GeoIP // RULE-SET,LAN
  - GEOSITE,cn,🔘 DIRECT
  - GEOIP,CN,🔘 DIRECT,no-resolve
  - GEOSITE,geolocation-!cn,🔰 Proxy
