# Quantumult X
# Date: 2026-04-10
# Author: @HotKids

[general]
[general]
profile_img_url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Want_Want.png
resource_parser_url=https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js
server_check_url=http://cp.cloudflare.com/generate_204
network_check_url=http://www.aliyun.com
;geo_location_checker=http://ifconfig.co/json, https://raw.githubusercontent.com/HotKids/Rules/master/Quantumult/X/GeoIP/IPConfig.js
geo_location_checker= http://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr, https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/IP_bili.js
;geo_location_checker=http://ip-api.com/json/?lang=zh-CN, https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/IP_API.js
dns_exclusion_list = *.lan, *.direct, cable.auth.com, *.msftconnecttest.com, *.msftncsi.com, network-test.debian.org, detectportal.firefox.com, resolver1.opendns.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, stun.*, global.turn.twilio.com, global.stun.twilio.com, app.yinxiang.com, injections.adguard.org, local.adguard.org, cable.auth.com, localhost.*.qq.com, localhost.*.weixin.qq.com, *.logon.battlenet.com.cn, *.logon.battle.net, *.blzstatic.cn, music.163.com, *.music.163.com, *.126.net, musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, *.kuwo.cn, api-jooxtt.sanook.com, api.joox.com, joox.com, y.qq.com, *.y.qq.com, streamoc.music.tc.qq.com, mobileoc.music.tc.qq.com, isure.stream.qqmusic.qq.com, dl.stream.qqmusic.qq.com, aqqmusic.tc.qq.com, amobile.music.tc.qq.com, *.xiami.com, *.music.migu.cn, music.migu.cn, proxy.golang.org, *.mcdn.bilivideo.cn, *.cmpassport.com, id6.me, open.e.189.cn, opencloud.wostore.cn, id.mail.wo.cn, mdn.open.wo.cn, hmrz.wo.cn, nishub1.10010.com, enrichgw.10010.com, *.wosms.cn, *.jegotrip.com.cn, *.icitymobile.mobi, *.pingan.com.cn, *.cmbchina.com, *.10099.com.cn, *.microdone.cn, pool.ntp.org, *.pool.ntp.org, ntp.*.com, time.*.com, ntp?.*.com, time?.*.com, time.*.gov, time.*.edu.cn, *.ntp.org.cn, PDC._msDCS.*.*, DC._msDCS.*.*, GC._msDCS.*.*
;running_mode_trigger=filter, filter, JOEY:all_direct
;ssid_suspended_list=HotKids
udp_whitelist=53, 80-427, 444-65535
excluded_routes= 192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8
;icmp_auto_reply=true

[dns]
server=119.29.29.29
server=119.28.28.28
server=223.5.5.5
server=223.6.6.6
server=180.76.76.76
server=1.2.4.8

# 引用自 https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/snippet/DNS.snippet
<< https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/snippet/DNS.snippet

[policy]
# Inbound // Outbound
static=Inbound, direct, img-url=https://raw.githubusercontent.com/HotKids/Rules/master/Quantumult/X/Images/Color/Inbound.png
# AdBlock
static=AdBlock, reject, direct, img-url=https://raw.githubusercontent.com/HotKids/Rules/master/Quantumult/X/Images/Color/AdBlock.png

[server_remote]
# https://sub.hotkids.me#udp=1&tfo=1&emoji=2, tag=Sub, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Airport.png, update-interval=86400, opt-parser=true, enabled=true

[filter_remote]

[rewrite_remote]
# 引用自脚本作者
# General 通用
# https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rewrite/QuantumultX/AllInOne/AllInOne.conf, tag=General, update-interval=86400, opt-parser=false, enabled=true
# Advertising 广告
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rewrite/QuantumultX/Advertising/Advertising.conf, tag=Advertising, update-interval=86400, opt-parser=false, enabled=true
# HttpDNS 阻止
https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/snippet/HTTPDNS.Block.snippet, tag=HttpDNS, update-interval=86400, opt-parser=false, enabled=true
# BoxJS
https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.quanx.conf, tag=BoxJS, update-interval=86400, opt-parser=false, enabled=true
# noredirect
https://raw.githubusercontent.com/zZPiglet/Task/master/noredirect.conf, tag=NoRedirect, update-interval=86400, opt-parser=false, enabled=true
# ChangeUA
https://raw.githubusercontent.com/zZPiglet/Task/master/ChangeUA.conf, tag=ChangeUA, update-interval=86400, opt-parser=false, enabled=true
# Startup 开屏广告
https://gist.githubusercontent.com/ddgksf2013/12ef6aad209155e7eb62c5b00c11b9dd/raw/StartUpAds.conf, tag=Startup, update-interval=86400, opt-parser=false, enabled=true
# 京东比价
https://raw.githubusercontent.com/githubdulong/Script/master/Surge/jd_price2.sgmodule, tag=京东比价, update-interval=86400, opt-parser=true, enabled=true
# 微博去广告
https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/WeiboAds.conf, tag=微博去广告, update-interval=86400, opt-parser=false, enabled=true
# 小红书去广告及水印（建议卸载重装）
https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/XiaoHongShuAds.conf, tag=小红书去广告, update-interval=86400, opt-parser=false, enabled=true
# 高德地图去广告（需卸载重装）
https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/AmapAds.conf, tag=高德地图去广告, update-interval=86400, opt-parser=false, enabled=true
# 喜马拉雅去广告（需卸载重装）
https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Ximalaya.conf, tag=喜马拉雅去广告, update-interval=86400, opt-parser=false, enabled=true
# 网易云音乐去广告
https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/NeteaseAds.conf, tag=网易云音乐去广告, update-interval=86400, opt-parser=false, enabled=true
# 菜鸟去广告
https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/CainiaoAds.conf, tag=菜鸟去广告, update-interval=86400, opt-parser=false, enabled=true
# 拼多多去广告
https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Pinduoduo.snippet, tag=拼多多去广告, update-interval=86400, opt-parser=true, enabled=true
# 滴滴出行去广告
https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Didichuxing.snippet, tag=滴滴出行去广告, update-interval=86400, opt-parser=true, enabled=false
# 酷安去广告
https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/KuAn.snippet, tag=酷安去广告, update-interval=86400, opt-parser=false, enabled=true
# Keep 去广告
https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Keep.snippet, tag=Keep 去广告, update-interval=86400, opt-parser=false, enabled=true
# Bilibili 去广告及功能增强
https://github.com/BiliUniverse/ADBlock/releases/latest/download/BiliBili.ADBlock.snippet, tag=BiliBili 去广告, update-interval=86400, opt-parser=false, enabled=true
https://github.com/BiliUniverse/Enhanced/releases/latest/download/BiliBili.Enhanced.snippet, tag=BiliBili 功能增强, update-interval=86400, opt-parser=false, enabled=true
# DualSubs 流媒体平台字幕增强及双语模块
https://github.com/DualSubs/Universal/releases/latest/download/DualSubs.Universal.snippet, tag=DualSubs, update-interval=86400, opt-parser=false, enabled=false

[task_local]
# remote
# GeoIP查询 - ip.sb by KOP-XIAO
event-interaction https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/geo_location.js, tag=GeoIP 查询, img-url=location.fill.viewfinder.system, enabled=true
# 流媒体解锁检测 by KOP-XIAO
event-interaction https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/streaming-ui-check.js, tag=流媒体解锁检测, img-url=checkmark.seal.system, enabled=true

[http_backend]
https://raw.githubusercontent.com/chavyleung/scripts/master/chavy.box.js, tag=BoxJS, path=^/, img-url=https://raw.githubusercontent.com/HotKids/Rules/master/Quantumult/X/Images/BoxJS.png, enabled=true

[server_local]

[filter_local]
# Unbreak 规则修正
host, ad.12306.cn, direct
host, sdkapp.uve.weibo.com, direct

# Local Area Network 局域网
host-suffix, local, direct
ip-cidr, 10.0.0.0/8, direct
ip-cidr, 127.0.0.0/8, direct
ip-cidr, 172.16.0.0/12, direct
ip-cidr, 192.168.0.0/16, direct
ip-cidr, 224.0.0.0/24, direct

;GeoIP China
-geoip, cn, direct

[rewrite_local]

[mitm]
passphrase =
p12 =
skip_validating_cert = false
force_sni_domain_name = true
