# Surfboard
# Date: 2026-04-10
# Author: @HotKids

[Proxy Group]
# Adblock // 📧 Mail
🚧 AdGuard = select, REJECT, DIRECT, icon-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Clubhouse_2.png
