# > KKBOX
USER-AGENT,*KKBOX,KKBOX&KKTV
DOMAIN-SUFFIX,kkbox.com,KKBOX&KKTV
DOMAIN-SUFFIX,kkbox.com.tw,KKBOX&KKTV
DOMAIN-SUFFIX,kfs.io,KKBOX&KKTV

# > KKTV
USER-AGENT,KKTV*,KKBOX&KKTV
USER-AGENT,com.kktv*,KKBOX&KKTV
DOMAIN-SUFFIX,kktv.me,KKBOX&KKTV
DOMAIN-SUFFIX,kktv.com.tw,KKBOX&KKTV
DOMAIN,kktv-theater.kk.stream,KKBOX&KKTV
