[General]
#!include https://raw.githubusercontent.com/HotKids/Rules/master/Surge/Profile.conf

[Host]
#!include https://raw.githubusercontent.com/HotKids/Rules/master/Surge/Profile.conf

[Ponte]
#!include https://raw.githubusercontent.com/HotKids/Rules/master/Surge/Profile.conf

[Proxy]
// 只需将 Subscription.conf 替换为机场订阅文件名即可。
#!include https://raw.githubusercontent.com/HotKids/Rules/master/Surge/Profile.conf, Subscription.conf

[Proxy Group]
#!include https://raw.githubusercontent.com/HotKids/Rules/master/Surge/Profile.conf

[Rule]
#!include https://raw.githubusercontent.com/HotKids/Rules/master/Surge/Profile.conf

[MITM]
#!include https://raw.githubusercontent.com/HotKids/Rules/master/Surge/Profile.conf
